# Generated by Django 4.2.5 on 2023-09-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_alter_maillog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Полное имя'),
        ),
    ]
