# Generated by Django 4.2.5 on 2023-09-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_alter_client_comment_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maillog',
            name='last_sent',
            field=models.DateTimeField(verbose_name='Дата и время последней рассылки'),
        ),
        migrations.AlterField(
            model_name='maillog',
            name='server_response',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ответ почтового сервера'),
        ),
        migrations.AlterField(
            model_name='maillog',
            name='status',
            field=models.CharField(max_length=100, verbose_name='Статус попытки'),
        ),
    ]
