# Generated by Django 4.2.5 on 2023-10-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0008_newsletter_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maillog',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последней рассылки'),
        ),
    ]
