# Generated by Django 4.2.5 on 2023-10-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0011_alter_newsletter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('completed', 'Завершена'), ('off', 'Отключена')], default='created', max_length=10, verbose_name='Статус'),
        ),
    ]
